name: Daily Firebase Report

on:
  schedule:
    - cron: '30 3 * * *'
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  send-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create service account file
        run: |
          echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service-account.json

      - name: Build and package
        run: mvn clean package -DskipTests

      - name: Run
        run: java -cp target/firebase-report-0.0.1-SNAPSHOT.jar:target/dependency/* com.firebase.report.firebase_report.FirebaseReport